### ISSUE TITLE
When pressing Ctrl + Up Google is getting closed.

### ISSUE THREAD

**Issue by Secrets123212** [Totsukawaii/UndownUnlock#1]
![image](https://github.com/Totsukawaii/UndownUnlock/assets/125499246/7d8594ba-771e-474e-8afe-cea188dbe230)

**Comment by Secrets123212** [comment]
I entered the lockdown, and it's still ongoing; it says 'Waiting for LockdDownBrowser.exe to start.'
![image](https://github.com/Totsukawaii/UndownUnlock/assets/125499246/ed273b1a-7985-46e8-b9cc-ce39663f677c)

**Comment by Secrets123212** [comment]
NVM JUST EDITED SOMETHING AND IT WORKED

**Comment by Secrets123212** [comment]
![image](https://github.com/Totsukawaii/UndownUnlock/assets/125499246/345dc8a6-91a7-40e2-a49a-9b17e5428ce2)
But screenshoot is not working its showing me this

**Comment by Totsukawaii** [comment]
what did you edit for it to work? 
Btw, even if you fix screenshot function screenshots don't work in lockdownbrowser because of DRM protection it will just produce a black image.

**Comment by Secrets123212** [comment]
I just changed the name from LockDownBrowser.exe to LockDownBrowserOEM.exe and it worked.

**Comment by adnan20071** [comment]
Hello, is there a way to take screen shoot or record in lockdown ?

**Comment by Totsukawaii** [comment]
> Hello, is there a way to take screen shoot or record in lockdown ?

currently No. I haven't found a way to bypass the drm

**Comment by adnan20071** [comment]
Can you find a way please

**Comment by Totsukawaii** [comment]
It's incredibly hard to bypass DRM. I've spent a week trying to figure it out with no luck. My best option was to use a man in the middle to capture the https response from my LMS and display it in my own browser to screenshot. Though this implementation is specific to my own school and you have to implement your own method till I find out a better way.

> Can you find a way please

**Comment by adnan20071** [comment]
I don't have any other method right now. Unfortunately, I tried searching but didn't find any. Anyway, thanks for this amazing tool.
