### ISSUE TITLE
injection successful but lockdown browser doesn't open/show

### ISSUE THREAD

**Issue by k7732** [Totsukawaii/UndownUnlock#10]
Controller

'activate.bat' is not recognized as an internal or external command,
operable program or batch file.
Environment 'lockdown' not found. Creating...
'conda' is not recognized as an internal or external command,
operable program or batch file.
'activate.bat' is not recognized as an internal or external command,
operable program or batch file.
Requirement already satisfied: keyboard==0.13.5 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 1)) (0.13.5)
Requirement already satisfied: Pillow==10.2.0 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 2)) (10.2.0)
Requirement already satisfied: psutil==5.9.6 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 3)) (5.9.6)
Requirement already satisfied: PyQt5==5.15.10 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 4)) (5.15.10)
Requirement already satisfied: PyQt5_sip==12.13.0 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 5)) (12.13.0)
Requirement already satisfied: pywin32==306 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 6)) (306)
Requirement already satisfied: PyWinCtl==0.3 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 7)) (0.3)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from PyQt5==5.15.10->-r requirements.txt (line 4)) (5.15.2)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from PyWinCtl==0.3->-r requirements.txt (line 7)) (4.10.0)
Requirement already satisfied: pywinbox>=0.6 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from PyWinCtl==0.3->-r requirements.txt (line 7)) (0.6)
Requirement already satisfied: pymonctl>=0.6 in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from PyWinCtl==0.3->-r requirements.txt (line 7)) (0.7)
Running...

Inject

'activate.bat' is not recognized as an internal or external command,
operable program or batch file.
Environment 'lockdown32' not found. Creating...
'conda' is not recognized as an internal or external command,
operable program or batch file.
'activate.bat' is not recognized as an internal or external command,
operable program or batch file.
Requirement already satisfied: psutil in c:\users\query\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements32.txt (line 1)) (5.9.6)
Running...
Waiting for a LockDown Browser process to start...
Found LockDownBrowser.exe with PID: 14936
DLL injected successfully!
Press any key to continue . . .

**Comment by Totsukawaii** [comment]
looks like you didn't install miniconda. try repeat the installation steps in the readme. also make sure your path has no spaces or brackets
