### ISSUE TITLE
DLL Injection

### ISSUE THREAD

**Issue by Jex1906** [Totsukawaii/UndownUnlock#17]
Everytime I open up the controller and Inject batch files in adminstrator mode then go into lockdown browser it shows me Found Lockdown Browser then says The handle is invalid DLL Injection Failed trying in 1 second again.

I've already tried 1.02 as well and its the same issue.

However everytime I open up lockdown browser it still lets me use the cntrl left and right it just doesn't say dll injected when opening it.
![image](https://github.com/Totsukawaii/UndownUnlock/assets/123091859/7670c012-7f1c-480c-bfcf-9a0444f9694b)

**Comment by Totsukawaii** [comment]
I've attempted to fix this issue in [v1.0.4](https://github.com/Totsukawaii/UndownUnlock/releases/download/v1.0.4/UndownUnlock-v1.0.4.zip)

Tell me if it works

**Comment by Jex1906** [comment]
Alright. Ill test it right now.

**Comment by Jex1906** [comment]
Alright Well I get this issue should I use controller 1.03 and injector 1.04?
![image](https://github.com/Totsukawaii/UndownUnlock/assets/123091859/62df040f-74da-4b3e-8c2b-79396f9b1c23)
for controller 1.04 it says this..

**Comment by Jex1906** [comment]
Im going to try to change the extraction name with no dashes.

**Comment by Jex1906** [comment]
I made another issue request as well. I have a test right now Ill see if 1.03 works cause it still functions and everything so just says "Dll not injeced"

**Comment by Jex1906** [comment]
Alr I redownloaded it downloaded micoarda and changed it to have no dashes, and its saying "running now and etc" so i think were good 2 go.
