### ISSUE TITLE
DLL Injection for 1.04

### ISSUE THREAD

**Issue by Jex1906** [Totsukawaii/UndownUnlock#18]
Still says the same thing and now the controller wont work.
![image](https://github.com/Totsukawaii/UndownUnlock/assets/123091859/51a4a990-cba5-4781-bd4c-285400ab9844)

**Comment by Totsukawaii** [comment]
Resolved in https://github.com/Totsukawaii/UndownUnlock/issues/17#issuecomment-2048012520
