### ISSUE TITLE
Amazing. Just a question.

### ISSUE THREAD

**Issue by Buckll69** [Totsukawaii/UndownUnlock#19]
Works perfectly it seems so far, need to get into an actual t3st. Is there anywhere I can PM you, I'm wondering if you've bypassed the pr0fs ability to see the time we are off LDB.

**Comment by Totsukawaii** [comment]
What do you mean time you are off LDB?

**Comment by Totsukawaii** [comment]
I'm pretty sure the 4 finger swipe gesture is still detected, you should use ctrl + arrow keys to alt-tab. Also I'm pretty sure they won't be able to detect that you have alt-tabbed because the injected DLL makes LDB think it's always in the foreground.

**Comment by XEnoner6** [comment]
Excuse me, I want to ask if you have a DLL suitable for win64. I have tested the following and found that the DLL is limited to Win32 version

**Comment by XEnoner6** [comment]
Excuse me, I want to ask if you have a DLL suitable for win64. I have tested the following and found that the DLL is limited to Win32 version

**Comment by Buckll69** [comment]
> I think the 4 finger swipe gesture is still detected by LDB, you should use ctrl + arrow keys to alt-tab. Also I'm pretty sure they won't be able to detect that you have alt-tabbed because the injected DLL makes LDB think it's always in the foreground.

That is perfect, along as it doesn't recognize when the page is left with CTRL up. 

Also I am running on 64 bit windows and latest release worked fine.
