### ISSUE TITLE
Detectability.

### ISSUE THREAD

**Issue by cynxothlexia** [Totsukawaii/UndownUnlock#2]
I've had some issues setting it up but after rewriting the injector's code I got it to work fine. My question is how detectable is it? Assuming that the browser doesn't detect it and lets you switch windows means that it doesn't detect it but correct me if I'm wrong. Now missing 3 months of college isn't going to backfire. Thank you <3333

**Comment by Totsukawaii** [comment]
welcome! may I know what's the code you changed to get it to work?

**Comment by cynxothlexia** [comment]
Nothing really, just changed the target exe's name in the injector's code. As when I tried changing the name of the actual exe in program files it wouldn't let me take my test. I just finished my test and it worked flawlessly. Once again thank you <3

**Comment by Totsukawaii** [comment]
About detectability, as I mentioned it's use at your own risk. I personally did a man in the middle on my own lockdown browser and it seems to be only sending video and images to the server. So I assume it's not recording the screen or mouse movements.

**Comment by cynxothlexia** [comment]
Well my college has our webcams blocked out by a physical piece so that's fine. Doesn't really matter as we take our exams in the presence of  a professor. The image part might be a bad thing but I guess it's whatever, they just focus on the submitted result and that's it.

**Comment by Totsukawaii** [comment]
> Well my college has our webcams blocked out by a physical piece so that's fine. Doesn't really matter as we take our exams in the presence of a professor. The image part might be a bad thing but I guess it's whatever, they just focus on the submitted result and that's it. Also do you plan on updating the injector? Every update patches are made and it's like a cat and mouse chase. ThreatningYeti for example shutdown due to this.

I have no idea about ThreatningYeti. I checked it out a bit, it seems he was using static memory addresses to hook the GetForeground Function, so whenever the lockdown browser updates the memory address in which the function is loaded at runtime is changed so you would probably need to find it again and update the static memory every update. My implementation doesn't use any static memory addresses so I don't think it's a problem.

**Comment by cynxothlexia** [comment]
Alright, thank you.

**Comment by Pratik7000** [comment]
HII I have my exam tomorrow and i have tried and tested right now without any exam and the switching tabs function seems to be fine.but i am in a doubt will it work during exam and it wont detect typing while using chatgpt right?
