### ISSUE TITLE
Careful hooking ntquery my guy

### ISSUE THREAD

**Issue by uhohspaghettioo** [Totsukawaii/UndownUnlock#22]
I have my own hack I developed with a custom injector. everything was lovely until i got greedy and hid processes thru ntquery. not sure what happened but I was detected on a practice quiz. Happy to share what I've done to help u stay FUD, but be careful. I dont use a hooking library and I dont even use first line API hooks so they arent detecting hooking, its anomaly detection 

shoot me an email uhohspaghettioo@proton.me if you want to compare versions and know what I think got me flagged (opsec wink wink)

**Comment by uhohspaghettioo** [comment]
ps you got all the skids in ur issues LMAO

**Comment by uhohspaghettioo** [comment]
also since I have to bow out ill give u my injector lolz

**Comment by uhohspaghettioo** [comment]
close and delete if u wanna resolve this behind close doors :)

**Comment by uhohspaghettioo** [comment]
> I have a question for you: how did you know you were detected ?
> 
> did LDB kicked you and you got warning or what

lil more than a warnin lolz

**Comment by fri12013** [comment]
They threatened to suspend your account from useing LDB if you tried to bypass it again, right?

**Comment by uhohspaghettioo** [comment]
> Hahahaha They threatened to suspend your account from useing LDB if you tried to bypass it again, right?

hello mr developer, im assuming you saw it too? so did threatening yeti id guess lmfao.

**Comment by Totsukawaii** [comment]
> suspend your account

I emailed you. And nope I haven't gotten a suspension warning yet.
