### ISSUE TITLE
FileNotFoundError DLLHooks.dll not found

### ISSUE THREAD

**Issue by amv01** [Totsukawaii/UndownUnlock#4]
Hello,
I have this problem when I run the injector:

<img width="679" alt="Immagine 2024-03-19 042012" src="https://github.com/Totsukawaii/UndownUnlock/assets/105238995/0a0f9794-657a-44e7-8f87-6e21245af6ca">

What am I doing wrong?

**Comment by Totsukawaii** [comment]
download the asset with the dll file not the source code. https://github.com/Totsukawaii/UndownUnlock/releases/download/v1.0.2/UndownUnlock-v1.0.2.zip
