### ISSUE TITLE
[question] does camera stay enabled when you switch off of lockdown?

### ISSUE THREAD

**Issue by yoyomomo21** [Totsukawaii/UndownUnlock#5]
hey, most of my classes enable the camera for lockdown browser tests, so i wanted to know does the cam stay on when you switch between apps?

and this:
"Is the DLL malware?
 - yes "
 
 its a joke right? im honestly not in the right mind right now so i wanna make sure that this is a joke.
 
 ty for answer in advance :)

**Comment by Totsukawaii** [comment]
The camera does stay on.

for the second point you can check for yourself
https://www.virustotal.com
