### ISSUE TITLE
Can i use it inside VM machine?

### ISSUE THREAD

**Issue by HeKtOr92** [Totsukawaii/UndownUnlock#6]
Hello my friend..thank you for this what you did is amazing 
I'm using VMware virtual machine because i have webcam driver problem in the host system but my webcam work fine in the VM.

so dose it work on VM or not? if not can you make it work please

**Comment by fri12013** [comment]
no Because you can,t run the LDB inside the VM without chenging Many things in the VM

**Comment by Totsukawaii** [comment]
bypassing vm detection is possible through dll injection, though I won't be implementing it. look here for more details on implementing your own vm bypass. https://systemfailu.re/2020/11/14/lockdownbrowser-analysis/
